spring.application.name=Spring_04
server.port=8080

# 기존 SQLite 설정 주석 처리 또는 삭제
# spring.datasource.url=jdbc:sqlite:mydb.db
# spring.datasource.driver-class-name=org.sqlite.JDBC

# GCP MySQL 설정 추가
spring.datasource.url=jdbc:mysql://34.81.209.172:3306/service_schema?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=Skotle
spring.datasource.password=@A09ajdud21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#--enable-native-access=ALL-UNNAMED
spring.datasource.hikari.maximum-pool-size=10 

# 아래 추가
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ao0rjdjur7xj@gmail.com
spring.mail.password=tlandsxlijjiuwmw
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.gcs.bucket-name=irisen-alpha
app.gcs.public-base-url=https://storage.googleapis.com
